server:
  port: 8762
spring:
  application:
    name: configcenter
  profiles:
    active: native  #配置文件获取方式，native表示从本地获取
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared  #本地配置文件存放的路径，classpath表示当前文件所在目录